{% set name = "umap-learn" %}
{% set version = "0.5.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lmcinnes/umap/archive/refs/tags/release-{{ version }}.tar.gz
  sha256: 79ef064f7132b77f9fdc99fb7fb4e902c72078c867f1ec6734388c1a7602854f

  patches:
    # see PR: https://github.com/lmcinnes/umap/pull/1063
    - patches/002_fix-relative-import-in-test.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - numpy >=1.23
    - scipy >=1.3.1
    - scikit-learn >=1.6
    - numba >=0.51.2
    - pynndescent >=0.5
    - tqdm
  run_constraint:
    - tensorflow >=2.1
    - tbb >=2019.0

test:
  source_files:
    - umap/tests
  imports:
    - umap
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # pyargs not work becasue result pkg don`t have umap/tests folder.
    - pytest umap/tests --show-capture=no -v --disable-warnings
  requires:
    - pip
    - pytest
    - pandas
    - matplotlib-base
    - datashader
    - bokeh
    - holoviews
    - colorcet
    - seaborn
    - dask
    - scikit-image

about:
  home: https://github.com/lmcinnes/umap
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Uniform Manifold Approximation and Projection
  description: |
    umap-learn provides the UMAP manifold based dimension reduction
    algorithm. The package provides an sklearn compatible interface
    to t-SNE like dimension reduction technique that has better
    runtime performacne than t-SNE and often preserves more global
    structure than t-SNE.
  dev_url: https://github.com/lmcinnes/umap
  doc_url: https://umap-learn.readthedocs.io

extra:
  recipe-maintainers:
    - lmcinnes
  skip-lints:
    - missing_pip_check  # [unix and x86_64]
