{% set name = "umap-learn" %}
{% set version = "0.3.8" %}
{% set sha256 = "f688060bce5495c06cb3e52df0982a63bb7b7755393b9f30e08e0c1791520d15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and py27 or win32]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - setuptools
    - numpy >=1.13
    - numba >=0.35
    - scikit-learn >=0.19
    - scipy >=0.18

test:
  imports:
    - umap

about:
  home: http://github.com/lmcinnes/umap
  license: BSD-2-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Uniform Manifold Approximation and Projection'

  description: |
    umap-learn provides the UMAP manifold based dimension reduction
    algorithm. The package provides an sklearn compatible interface
    to t-SNE like dimension reduction technique that has better 
    runtime performacne than t-SNE and often preserves more global
    structure than t-SNE.
  dev_url: https://github.com/lmcinnes/umap

extra:
  recipe-maintainers:
    - lmcinnes
