{% set name = "umap-learn" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lmcinnes/umap/archive/refs/tags/{{ version }}.tar.gz
  sha256: 067a1724cf9edfa5c32c791fae908361c402af97f3fbbec2b231503dfe057bc8

  patches:
    # version 0.5.4 brings in tbb as a dependency, but installing it is not
    # seen by pip and pip check will fail.
    # It seems that at the end it is an optional dependency
    # see here: https://github.com/lmcinnes/umap/issues/1060#issuecomment-1749511918
    # Therefore, we remove it from the dependencies
    - patches/001_remove-tbb-dependency.patch
    - patches/002_fix-relative-import-in-test.patch

build:
  number: 0
  # depends on numba not available for linux-s390x
  skip: true  # [py<36 or s390x]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - numpy >=1.17
    - numba >=0.51.2
    - scikit-learn >=0.22
    - scipy >=1.3.1
    - pynndescent >=0.5
    - tqdm
    - tbb >=2019.0  # [x86_64]

test:
  requires:
    - pip
    - pytest
    # [plot]
    - pandas
    - matplotlib
    - datashader
    - bokeh
    - holoviews
    - colorcet
    - seaborn
    - scikit-image
    # [parametric_umap]
    # disable tensorflow for the moment 
    # - tensorflow >= 2.12
    # - tensorflow-probability >= 0.14
  imports:
    - umap
  source_files:
    - umap/tests
  commands:
    - pip check
    - python -m pytest umap/tests --show-capture=no -v --disable-warnings

about:
  home: https://github.com/lmcinnes/umap
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Uniform Manifold Approximation and Projection
  description: |
    umap-learn provides the UMAP manifold based dimension reduction
    algorithm. The package provides an sklearn compatible interface
    to t-SNE like dimension reduction technique that has better
    runtime performacne than t-SNE and often preserves more global
    structure than t-SNE.
  dev_url: https://github.com/lmcinnes/umap
  doc_url: https://umap-learn.readthedocs.io

extra:
  recipe-maintainers:
    - lmcinnes
