{% set name = "umap-learn" %}
{% set version = "0.5.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lmcinnes/umap/archive/refs/tags/release-{{ version }}.tar.gz
  sha256: 79ef064f7132b77f9fdc99fb7fb4e902c72078c867f1ec6734388c1a7602854f

  patches:
    # see PR: https://github.com/lmcinnes/umap/pull/1063
    - patches/002_fix-relative-import-in-test.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # numpy<1.24 not avaliable on py>311
  skip: true  # [py<39]

requirements:
  build:
    - patch  # [not win]
    - msys2-patch  # [win]
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - numpy >=1.23
    - scipy >=1.3.1
    - scikit-learn >=1.6
    - numba >=0.51.2
    - pynndescent >=0.5
    - tqdm

# >   raise e.with_traceback(None)
# E   numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
{% set deselect_tests = " --deselect=umap/tests/test_plot.py::test_plot_runs_at_all" %}
# >   raise TypeError(msg % type(expected_warning))
# E   TypeError: exceptions must be derived from Warning, not <class 'NoneType'>
{% set deselect_tests = deselect_tests + " --deselect=umap/tests/test_umap_ops.py::test_disconnected_data" %}
# >   assert len(warnings) <= 1
# E   assert 2 <= 1
# E    +  where 2 = len(WarningsChecker(record=True))
{% set deselect_tests = deselect_tests + " --deselect=umap/tests/test_umap_validation_params.py::test_umap_custom_distance_w_grad" %}
# >   assert error < 3.0  # Higher error tolerance based on approx nearest neighbors
# E   assert 17.72839 < 3.0
{% set deselect_tests = deselect_tests + " --deselect=umap/tests/test_umap_ops.py::test_umap_update_large" %}
# E   AssertionError: tsvd-warmed spectral init insufficiently close to standard spectral init
# E       assert 0.200000000003558 < 1e-06
{% set deselect_tests = deselect_tests + " --deselect=umap/tests/test_spectral.py::test_tsw_spectral_init" %}
# Fatal Python error: Segmentation fault
{% set deselect_tests = deselect_tests + " --deselect=umap/tests/test_umap_validation_params.py::test_umap_update_bad_params" %}  # [linux]

test:
  source_files:
    - umap/tests
  imports:
    - umap
  commands:
    # pywavelets 1.5.0 has requirement numpy<2.0,>=1.22.4, but you have numpy 1.21.6.
    - pip check  # [not (unix and x86_64)]
    # pyargs not work becasue result pkg don`t have umap/tests folder.
    - pytest umap/tests {{ deselect_tests }} --show-capture=no -v --disable-warnings
  requires:
    - pip
    - pytest
    - pandas
    - matplotlib-base
    - datashader
    - bokeh
    - holoviews
    - colorcet
    - seaborn
    - scikit-image

about:
  home: https://github.com/lmcinnes/umap
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Uniform Manifold Approximation and Projection
  description: |
    umap-learn provides the UMAP manifold based dimension reduction
    algorithm. The package provides an sklearn compatible interface
    to t-SNE like dimension reduction technique that has better
    runtime performacne than t-SNE and often preserves more global
    structure than t-SNE.
  dev_url: https://github.com/lmcinnes/umap
  doc_url: https://umap-learn.readthedocs.io

extra:
  recipe-maintainers:
    - lmcinnes
  skip-lints:
    - missing_pip_check  # [unix and x86_64]
