{% set name = "umap-learn" %}
{% set version = "0.5.4" %}
{% set sha256 = "8cb2fa20b2493f9adbff3bfa3b3e3787f6d67d1547e688ea2bdc272b37d89e18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # depends on numba not available for linux-s390x
  skip: true  # [py<36 or s390x]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - numpy >=1.17
    - numba >=0.51.2
    - scikit-learn >=0.22
    - scipy >=1.3.1
    - pynndescent >=0.5
    - tqdm
    - tbb >=2019.0  # [x86_64]

test:
  requires:
    - pip
  imports:
    - umap
  commands:
    - pip check

about:
  home: https://github.com/lmcinnes/umap
  license: BSD-2-Clause
  license_family: BSD
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Uniform Manifold Approximation and Projection

  description: |
    umap-learn provides the UMAP manifold based dimension reduction
    algorithm. The package provides an sklearn compatible interface
    to t-SNE like dimension reduction technique that has better
    runtime performacne than t-SNE and often preserves more global
    structure than t-SNE.
  dev_url: https://github.com/lmcinnes/umap
  doc_url: https://umap-learn.readthedocs.io

extra:
  recipe-maintainers:
    - lmcinnes
