travis:
  secure:
    BINSTAR_TOKEN: XL9c4Tc17zMz1WXiDQiP5f6inAnsfVGhunNFShWdMku+OclNUGnfeIQYtF6R3Bzbi/VchZfm5slFOJBFB3DjkVK+waz0eBe2Ck1/vuDIvTWiZAWJEFMAUn6OyJRuKuQFdksl4HbRfS3TFXqbd10Mgnd1SqeeLtSGxOGE216+ooLcwpESNSlMlEy2o2PiypwsO4byzePxG7g4JYVbol//AbCH0HJch3d8lygwd6v+1Aegh92i/WkheDKUmZgfjOu34V4dJcoIQ5fPQQylaj58unUtWcMaD8Yn3iST3u0O9yBvwN8rm5nRMOZKWNwtUyYkFlQgBraLl245F+njN/Smk0FKpI6L47qh1YNk3eD5XbcgUs7vn64bb8zQrx8nU+gIJmgHSd75I+1WEjjisiLQvaMM/MB3CAgieorRyivgmQb2iXJbxMOabepF8rEqYEbaNQRlenHsRheuCn9RgYVOKmEjP1LwJbOHgHNRDbZnUH0P9sDJr1CqrEvTfq4SECI/GPStHtAq+EhldVHMbnJUSnuu9uXLPlKgwQlU8H5aoA/FBqXhwLNjfyvcpqAQRUZwDoiUxTin5kK0Q4ebmy8KwMHybiO+aheOz/VSxymCaJUBs4LkCJMnKdCHL/yMTuUERO40McYQdz3ViXzdPawKWr+YCq/ZMLOIOeRArrpkgsU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
