appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: I4E4cXR2twYkSUUbrue6rM2mL7nrWXYTd8FINogJgyTsTlF5n+CqnqpeBETwPXuTqOsOiCZ6uMNGoCood6C/iYLi4haYz26BWL57ljXb544JsyDl2MzZQkL0BpxWxtF7eDEVy97V6Eo8BEYROHEAQz2ILQUTWl6FFEO6/Ck4BLqK4wTrmONI5wEaTp9ZSxanMTjh8lIQ4F4vGAa4uy4TeVJC1TSrzjBb+Ihv3m60mH0kujPtGDi6Mf7yWf7QcjhGijMihYh9q1AywNQh2+GRQEblXZpe2yRaOy6IbLOCVJAMu5HiKYzFMDO4WGXP564mS3Uh+FLGILu6pcL64ZPUkVagLP/2k7+4/NcN1oweFmeHvylY+KOwrhZy6ANdDH3RRXODz4rqyWp5gkbf/GCvPzXJpVigsJ7Rhn1G7kaNeSWLDXl8VOmS8Pvd/STosUb63uv0/obz3CmE5AjIuQAq/dHXca9m81LYnpz6VTspTrEknwnzyakcql0Z/aD+MA+U+UVu4ElvKZMesOepAUWveq41b35V9pOI4s5oqsa3grnl7XM/01XNBQ/og/999Cu5bR2s1qgOOizpme3jgQyHieNJnn7M0xt0MWTCcj3NIvGD1Ev4Q7/XCXvnEIHLJtHazmtRs2S6GicHyUzMFNrEdZxSnyX9idRZLNi+HTi6MX4=}
